name:                elm-type-inference
version:             0.1.0.0
github:              "emilyhorsman/elm-type-inference"
license:             BSD3
author:              "Emily Horsman"
maintainer:          "me@emilyhorsman.com"
copyright:           "2018 Emily Horsman"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emilyhorsman/elm-type-inference#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.0.1 && < 0.7
- megaparsec >= 7.0.1 && < 7.1

library:
  source-dirs: src

executables:
  elm-type-inference-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-type-inference

tests:
  elm-type-inference-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-type-inference
    - hspec >= 2.5.5 && < 3
    - hspec-megaparsec >= 2.0.0 && < 3
    - raw-strings-qq >= 1.1 && < 2
