-- GENERATED WITH FilterTypeAnnotations.py vendor/core/src/Basics.elm --
-- DO NOT EDIT MANUALLY --
module Elm.Basics where

source :: [String]
source = [
   "add : number -> number -> number",
   "sub : number -> number -> number",
   "mul : number -> number -> number",
   "fdiv : Float -> Float -> Float",
   "idiv : Int -> Int -> Int",
   "pow : number -> number -> number",
   "toFloat : Int -> Float",
   "round : Float -> Int",
   "floor : Float -> Int",
   "ceiling : Float -> Int",
   "truncate : Float -> Int",
   "eq : a -> a -> Bool",
   "neq : a -> a -> Bool",
   "min : comparable -> comparable -> comparable",
   "max : comparable -> comparable -> comparable",
   "compare : comparable -> comparable -> Order",
   "not : Bool -> Bool",
   "and : Bool -> Bool -> Bool",
   "or : Bool -> Bool -> Bool",
   "xor : Bool -> Bool -> Bool",
   "append : appendable -> appendable -> appendable",
   "modBy : Int -> Int -> Int",
   "remainderBy : Int -> Int -> Int",
   "negate : number -> number",
   "abs : number -> number",
   "clamp : number -> number -> number -> number",
   "sqrt : Float -> Float",
   "logBase : Float -> Float -> Float",
   "e : Float",
   "radians : Float -> Float",
   "degrees : Float -> Float",
   "turns : Float -> Float",
   "pi : Float",
   "cos : Float -> Float",
   "sin : Float -> Float",
   "tan : Float -> Float",
   "acos : Float -> Float",
   "asin : Float -> Float",
   "atan : Float -> Float",
   "atan2 : Float -> Float -> Float",
   "fromPolar : (Float,Float) -> (Float,Float)",
   "toPolar : (Float,Float) -> (Float,Float)",
   "isNaN : Float -> Bool",
   "isInfinite : Float -> Bool",
   "composeL : (b -> c) -> (a -> b) -> (a -> c)",
   "composeR : (a -> b) -> (b -> c) -> (a -> c)",
   "apR : a -> (a -> b) -> b",
   "apL : (a -> b) -> a -> b",
   "identity : a -> a",
   "always : a -> b -> a",
   "never : Never -> a"]
